<?php
/**
 * Systempay V2-Payment Module version 1.7.1 for Magento 1.4-1.9. Support contact : supportvad@lyra-network.com.
 *
 * NOTICE OF LICENSE
 *
 * This source file is licensed under the Open Software License version 3.0
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category  payment
 * @package   systempay
 * @author    Lyra Network (http://www.lyra-network.com/)
 * @copyright 2014-2017 Lyra Network and contributors
 * @license   http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>

<?php if (Mage::getModel('systempay/payment_standard')->isOneclickAvailable()) : ?>
    <script type="text/javascript">
    //<![CDATA[
        var systempayUpdatePaymentBlock = function(blockName) {
            $$('ul#payment_form_systempay_standard li').invoke('hide');
            $$('ul#payment_form_systempay_standard li input').invoke('disable');
            $$('ul#payment_form_systempay_standard li select').invoke('disable');

            $$('li.systempay-standard-' + blockName + '-block').invoke('show');
            $$('li.systempay-standard-' + blockName + '-block input').invoke('enable');
            $$('li.systempay-standard-' + blockName + '-block select').invoke('enable');
        };

        var onMethodSystempayStandardClick = function(event) {
            systempayUpdatePaymentBlock.delay(0.2, 'id');
        };

        var systempayUpdateShippingBlock = function() {
            var form, params = {};

            if (productAddToCartForm) { // if method called from product view
                form = $('product_addtocart_form');
            } else {
                form = $('systempay_cart_oneclick_form');
            }

            var validator  = new Validation(form, {stopOnFirst: true});

            if (!form || !validator.validate()) {
                // invalid form data
                return;
            }

            form.getElements().each(function(elt) {
                if (elt.name) {
                    params[elt.name] = elt.value;
                }
            });

            new Ajax.Request("<?php echo $this->getUrl('systempay/payment/oneclickShipping') ?>", {
                method: 'post',
                parameters: params,
                onLoading: function(){
                    $$('#' + form.id + ' .systempay-please-wait').invoke('show');
                    $$('#' + form.id + ' .systempay-shipping-method').invoke('hide');
                },
                onSuccess: function(transport) {
                    $$('#' + form.id + ' .systempay-please-wait').invoke('hide');
                    $$('#' + form.id + ' .systempay-shipping-method').invoke('show');

                    var response = transport.responseText.evalJSON();
                    if (response.error) {
                        alert(response.message);
                    }

                    if (response.html) {
                        $$('#' + form.id + ' .shipping_method').first().update(response.html);
                    }
                }
            });
        };

        var systempayProductOneclickPayment = function(button) {
            var form = $('product_addtocart_form');
            var validator  = new Validation(form);

            if (!form || !validator.validate()) {
                // invalid form data
                return;
            }

            var elts = $$('#' + form.id + ' .systempay-method-select');
            if (!elts || !elts.length || !elts.first().value) {
                return;
            }

            if (button) {
                button.disabled = true;
            }

            // override form action with Systempay 1-Click payment URL
            form.action = "<?php echo $this->getUrl('systempay/payment/oneclickPayment', array('_secure' => true)) ?>";
            form.submit();
        };
    //]]>
    </script>
<?php endif;?>